### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by zaaack** [bramschulting/no-dock-arrows#1]
Is this finished?

**Comment by giannisp** [comment]
Or you can directly add on your Atom->Stylesheet file the css snippet:
```css
.atom-dock-toggle-button-visible {
  display: none !important;
}
```

**Comment by zaaack** [comment]
@giannisp Thanks! I should think of this way earlier.

By the way, I'm using nuclide,  the CSS code should be
```css



.atom-dock-toggle-button,
.nuclide-workspace-views-toggle-button {
  display: none !important;
}
```

just for anyone searching for this issue :).
